---
abstract: 'parse CSS selectors to Perl data structures'
author:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Selector-Parser
requires:
  ExtUtils::MakeMaker: 6.11
  Sub::Exporter: 0
version: 0.001
